# Generated by Django 3.2.3 on 2021-06-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_userprofile_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daysadded',
        ),
    ]
