# Generated by Django 3.2.3 on 2021-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_userprofile_daysadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_added',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
