# Generated by Django 3.2.3 on 2021-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_expired_full_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_fee_pending',
            field=models.BooleanField(default=False),
        ),
    ]
