# Generated by Django 3.2.3 on 2021-07-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_rename_membership_fee_pending_userprofile_membership_fee_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='membership_fee_paid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_fee_due',
            field=models.IntegerField(default=0),
        ),
    ]
