# Generated by Django 3.2.3 on 2021-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210725_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_member',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
