# Generated by Django 3.2.3 on 2021-08-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_userprofile_full_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_fee_due',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
