# Generated by Django 3.2.3 on 2021-06-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.TextField(editable=False),
        ),
    ]
