# Generated by Django 3.2.3 on 2021-05-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workouts',
            options={'verbose_name_plural': 'Workouts'},
        ),
    ]
