# Generated by Django 3.2.3 on 2021-05-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workouts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='sku',
        ),
    ]
