# Generated by Django 3.2.3 on 2021-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_workouts_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
