# Generated by Django 3.2.3 on 2021-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workouts_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='video_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
