# Generated by Django 3.2.3 on 2021-05-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workouts_video_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='video_image_url',
            new_name='image_url',
        ),
    ]
