# Generated by Django 3.2.3 on 2021-08-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_workouts_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='video_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
