# Generated by Django 3.2.3 on 2021-07-25 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberblog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
