# Generated by Django 3.2.3 on 2021-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_blog', '0002_alter_memberblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
